Page({

  /**
   * 页面的初始数据
   */
  data: {
    left_menu_list:[{
      id:0,
      name:"大一",
      isActive:true
    },{
      id:1,
      name:"大二",
      isActive:false
    },{
      id:2,
      name:"大三",
      isActive:false
    },{
      id:3,
      name:"考研",
      isActive:false
    },{
      id:4,
      name:"四六级",
      isActive:false
    }],
    
    all_content:[
      [{
        id_1:0,
        name_1:"智能制造学院",
        content_1:[{
          id_2:0,
          name:"高等数学",
          src:"https://s1.ax1x.com/2020/09/05/wESbGt.jpg",
          cat_id:101,
          prince:20.5,
          author:"张三",
          version:"2019-08",
          original:68.5,
          publish:"光明出版社",
          type:"二手书"
        },{
          id_2:1,
          name:"机械制图",
          src:"https://s1.ax1x.com/2020/09/01/dvvV8x.jpg",
          cat_id:102,
          prince:10.0
        },{
          id_2:2,
          name:"1.3",
          src:"https://s1.ax1x.com/2020/09/01/dvvV8x.jpg",
          cat_id:103
        },{
          id_2:3,
          name:"1.4",
          src:"https://s1.ax1x.com/2020/09/01/dvvV8x.jpg",
          cat_id:104
        }]
      },{
        id_1:1,
        name_1:"软件学院",
        content_1:[{
          id_2:0,
          name:"2.1",
          src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png",
          cat_id:105
        },{
          id_2:1,
          name:"2.2",
          src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png",
          cat_id:106
        },{
          id_2:2,
          name:"2.3",
          src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png",
          cat_id:107
        },{
          id_2:3,
          name:"1.4",
          src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png",
          cat_id:108
        },{
          id_2:4,
          name:"1.5",
          src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png",
          cat_id:109
        }]
      },{
        id_1:2,
        name_1:"范蠡商学院",
        content_1:[{
          id_2:0,
          name:"1.1",
          src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png"
        },{
          id_2:1,
          name:"1.2",
          src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png"
        },{
          id_2:2,
          name:"1.3",
          src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png"
        },{
          id_2:3,
          name:"1.4",
          src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png"
        },{
          id_2:4,
          name:"1.5",
          src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png"
        },{
          id_2:5,
          name:"1.6",
          src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png"
        }]
      },{
        id_1:0,
        name_1:"智能制造学院",
        content_1:[{
          id_2:0,
          name:"1.1",
          src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png"
        },{
          id_2:1,
          name:"1.2",
          src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png"
        },{
          id_2:2,
          name:"1.3",
          src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png"
        },{
          id_2:3,
          name:"1.4",
          src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png"
        }]
      },{
        id_1:1,
        name_1:"软件学院",
        content_1:[{
          id_2:0,
          name:"2.1",
          src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png"
        },{
          id_2:1,
          name:"2.2",
          src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png"
        },{
          id_2:2,
          name:"2.3",
          src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png"
        },{
          id_2:3,
          name:"1.4",
          src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png"
        },{
          id_2:4,
          name:"1.5",
          src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png"
        }]
      },{
        id_1:3,
        name_1:"音乐学院",
        content_1:[{
          id_2:0,
          name:"1.1",
          src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png"
        },{
          id_2:1,
          name:"1.2",
          src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png"
        },{
          id_2:2,
          name:"1.3",
          src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png"
        },{
          id_2:3,
          name:"1.4",
          src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png"
        }]
      },{
        id_1:4,
        name_1:"张仲景国医国药学院",
        content_1:[{
          id_2:0,
          name:"2.1",
          src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png"
        },{
          id_2:1,
          name:"2.2",
          src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png"
        },{
          id_2:2,
          name:"2.3",
          src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png"
        },{
          id_2:3,
          name:"1.4",
          src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png"
        },{
          id_2:4,
          name:"1.5",
          src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png"
        }]
      }],
      [{
        id_1:0,
        name_1:"aaaa学院",
        content_1:[{
          id_2:0,
          name:"高数",
          src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png",
          prince:20.0
        },{
          id_2:1,
          name:"1.2",
          src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png"
        },{
          id_2:2,
          name:"1.3",
          src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png"
        },{
          id_2:3,
          name:"1.4",
          src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png"
        }]
      },{
        id_1:1,
        name_1:"软件学院",
        content_1:[{
          id_2:0,
          name:"2.1",
          src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png"
        },{
          id_2:1,
          name:"2.2",
          src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png"
        },{
          id_2:2,
          name:"2.3",
          src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png"
        },{
          id_2:3,
          name:"1.4",
          src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png"
        },{
          id_2:4,
          name:"1.5",
          src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png"
        }]
      },{
        id_1:2,
        name_1:"范蠡商学院",
        content_1:[{
          id_2:0,
          name:"1.1",
          src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png"
        },{
          id_2:1,
          name:"1.2",
          src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png"
        },{
          id_2:2,
          name:"1.3",
          src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png"
        },{
          id_2:3,
          name:"1.4",
          src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png"
        },{
          id_2:4,
          name:"1.5",
          src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png"
        },{
          id_2:5,
          name:"1.6",
          src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png"
        }]
      },{
        id_1:0,
        name_1:"智能制造学院",
        content_1:[{
          id_2:0,
          name:"1.1",
          src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png"
        },{
          id_2:1,
          name:"1.2",
          src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png"
        },{
          id_2:2,
          name:"1.3",
          src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png"
        },{
          id_2:3,
          name:"1.4",
          src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png"
        }]
      },{
        id_1:1,
        name_1:"软件学院",
        content_1:[{
          id_2:0,
          name:"2.1",
          src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png"
        },{
          id_2:1,
          name:"2.2",
          src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png"
        },{
          id_2:2,
          name:"2.3",
          src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png"
        },{
          id_2:3,
          name:"1.4",
          src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png"
        },{
          id_2:4,
          name:"1.5",
          src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png"
        }]
      },{
        id_1:3,
        name_1:"音乐学院",
        content_1:[{
          id_2:0,
          name:"1.1",
          src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png"
        },{
          id_2:1,
          name:"1.2",
          src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png"
        },{
          id_2:2,
          name:"1.3",
          src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png"
        },{
          id_2:3,
          name:"1.4",
          src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png"
        }]
      },{
        id_1:4,
        name_1:"张仲景国医国药学院",
        content_1:[{
          id_2:0,
          name:"2.1",
          src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png"
        },{
          id_2:1,
          name:"2.2",
          src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png"
        },{
          id_2:2,
          name:"2.3",
          src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png"
        },{
          id_2:3,
          name:"1.4",
          src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png"
        },{
          id_2:4,
          name:"1.5",
          src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png"
        }]
      }],
      [{
        id_1:0,
        name_1:"bbbb学院",
        content_1:[{
          id_2:0,
          name:"1.1",
          src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png"
        },{
          id_2:1,
          name:"1.2",
          src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png"
        },{
          id_2:2,
          name:"1.3",
          src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png"
        },{
          id_2:3,
          name:"1.4",
          src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png"
        }]
      },{
        id_1:1,
        name_1:"软件学院",
        content_1:[{
          id_2:0,
          name:"2.1",
          src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png"
        },{
          id_2:1,
          name:"2.2",
          src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png"
        },{
          id_2:2,
          name:"2.3",
          src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png"
        },{
          id_2:3,
          name:"1.4",
          src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png"
        },{
          id_2:4,
          name:"1.5",
          src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png"
        }]
      },{
        id_1:2,
        name_1:"范蠡商学院",
        content_1:[{
          id_2:0,
          name:"1.1",
          src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png"
        },{
          id_2:1,
          name:"1.2",
          src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png"
        },{
          id_2:2,
          name:"1.3",
          src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png"
        },{
          id_2:3,
          name:"1.4",
          src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png"
        },{
          id_2:4,
          name:"1.5",
          src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png"
        },{
          id_2:5,
          name:"1.6",
          src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png"
        }]
      },{
        id_1:0,
        name_1:"智能制造学院",
        content_1:[{
          id_2:0,
          name:"1.1",
          src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png"
        },{
          id_2:1,
          name:"1.2",
          src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png"
        },{
          id_2:2,
          name:"1.3",
          src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png"
        },{
          id_2:3,
          name:"1.4",
          src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png"
        }]
      },{
        id_1:1,
        name_1:"软件学院",
        content_1:[{
          id_2:0,
          name:"2.1",
          src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png"
        },{
          id_2:1,
          name:"2.2",
          src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png"
        },{
          id_2:2,
          name:"2.3",
          src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png"
        },{
          id_2:3,
          name:"1.4",
          src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png"
        },{
          id_2:4,
          name:"1.5",
          src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png"
        }]
      },{
        id_1:3,
        name_1:"音乐学院",
        content_1:[{
          id_2:0,
          name:"1.1",
          src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png"
        },{
          id_2:1,
          name:"1.2",
          src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png"
        },{
          id_2:2,
          name:"1.3",
          src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png"
        },{
          id_2:3,
          name:"1.4",
          src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png"
        }]
      },{
        id_1:4,
        name_1:"张仲景国医国药学院",
        content_1:[{
          id_2:0,
          name:"2.1",
          src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png"
        },{
          id_2:1,
          name:"2.2",
          src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png"
        },{
          id_2:2,
          name:"2.3",
          src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png"
        },{
          id_2:3,
          name:"1.4",
          src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png"
        },{
          id_2:4,
          name:"1.5",
          src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png"
        }]
      }],
      [{
        id_1:0,
        name_1:"eeeee学院",
        content_1:[{
          id_2:0,
          name:"1.1",
          src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png"
        },{
          id_2:1,
          name:"1.2",
          src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png"
        },{
          id_2:2,
          name:"1.3",
          src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png"
        },{
          id_2:3,
          name:"1.4",
          src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png"
        }]
      },{
        id_1:1,
        name_1:"软件学院",
        content_1:[{
          id_2:0,
          name:"2.1",
          src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png"
        },{
          id_2:1,
          name:"2.2",
          src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png"
        },{
          id_2:2,
          name:"2.3",
          src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png"
        },{
          id_2:3,
          name:"1.4",
          src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png"
        },{
          id_2:4,
          name:"1.5",
          src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png"
        }]
      },{
        id_1:2,
        name_1:"范蠡商学院",
        content_1:[{
          id_2:0,
          name:"1.1",
          src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png"
        },{
          id_2:1,
          name:"1.2",
          src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png"
        },{
          id_2:2,
          name:"1.3",
          src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png"
        },{
          id_2:3,
          name:"1.4",
          src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png"
        },{
          id_2:4,
          name:"1.5",
          src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png"
        },{
          id_2:5,
          name:"1.6",
          src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png"
        }]
      },{
        id_1:0,
        name_1:"智能制造学院",
        content_1:[{
          id_2:0,
          name:"1.1",
          src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png"
        },{
          id_2:1,
          name:"1.2",
          src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png"
        },{
          id_2:2,
          name:"1.3",
          src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png"
        },{
          id_2:3,
          name:"1.4",
          src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png"
        }]
      },{
        id_1:1,
        name_1:"软件学院",
        content_1:[{
          id_2:0,
          name:"2.1",
          src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png"
        },{
          id_2:1,
          name:"2.2",
          src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png"
        },{
          id_2:2,
          name:"2.3",
          src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png"
        },{
          id_2:3,
          name:"1.4",
          src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png"
        },{
          id_2:4,
          name:"1.5",
          src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png"
        }]
      },{
        id_1:3,
        name_1:"音乐学院",
        content_1:[{
          id_2:0,
          name:"1.1",
          src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png"
        },{
          id_2:1,
          name:"1.2",
          src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png"
        },{
          id_2:2,
          name:"1.3",
          src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png"
        },{
          id_2:3,
          name:"1.4",
          src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png"
        }]
      },{
        id_1:4,
        name_1:"张仲景国医国药学院",
        content_1:[{
          id_2:0,
          name:"2.1",
          src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png"
        },{
          id_2:1,
          name:"2.2",
          src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png"
        },{
          id_2:2,
          name:"2.3",
          src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png"
        },{
          id_2:3,
          name:"1.4",
          src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png"
        },{
          id_2:4,
          name:"1.5",
          src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png"
        }]
      }],
      [{
        id_1:0,
        name_1:"英语四级",
        content_1:[{
          id_2:0,
          name:"1.1",
          src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png"
        },{
          id_2:1,
          name:"1.2",
          src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png"
        },{
          id_2:2,
          name:"1.3",
          src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png"
        },{
          id_2:3,
          name:"1.4",
          src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png"
        }]
      },{
        id_1:1,
        name_1:"英语六级",
        content_1:[{
          id_2:0,
          name:"2.1",
          src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png"
        },{
          id_2:1,
          name:"2.2",
          src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png"
        },{
          id_2:2,
          name:"2.3",
          src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png"
        },{
          id_2:3,
          name:"1.4",
          src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png"
        },{
          id_2:4,
          name:"1.5",
          src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png"
        }]
      }],
    ],
    currentIndex:0,
    temp:[{
      id_1:0,
      name_1:"智能制造学院",
      content_1:[{
        id_2:0,
        name:"高等数学",
        src:"https://s1.ax1x.com/2020/09/05/wESbGt.jpg",
        cat_id:101,
        prince:20.5,
        author:"张三",
        version:"2019-08",
        original:68.5,
        publish:"光明出版社",
        type:"二手书"
      },{
        id_2:1,
        name:"机械制图",
        src:"https://s1.ax1x.com/2020/09/01/dvvV8x.jpg",
        cat_id:102,
        prince:10.0
      },{
        id_2:2,
        name:"1.3",
        src:"https://s1.ax1x.com/2020/09/01/dvvV8x.jpg",
        cat_id:103
      },{
        id_2:3,
        name:"1.4",
        src:"https://s1.ax1x.com/2020/09/01/dvvV8x.jpg",
        cat_id:104
      }]
    },{
      id_1:1,
      name_1:"软件学院",
      content_1:[{
        id_2:0,
        name:"2.1",
        src:"https://s1.ax1x.com/2020/09/01/dvvV8x.jpg",
        cat_id:105
      },{
        id_2:1,
        name:"2.2",
        src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png",
        cat_id:106
      },{
        id_2:2,
        name:"2.3",
        src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png",
        cat_id:107
      },{
        id_2:3,
        name:"1.4",
        src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png",
        cat_id:108
      },{
        id_2:4,
        name:"1.5",
        src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png",
        cat_id:109
      }]
    },{
      id_1:2,
      name_1:"范蠡商学院",
      content_1:[{
        id_2:0,
        name:"1.1",
        src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png"
      },{
        id_2:1,
        name:"1.2",
        src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png"
      },{
        id_2:2,
        name:"1.3",
        src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png"
      },{
        id_2:3,
        name:"1.4",
        src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png"
      },{
        id_2:4,
        name:"1.5",
        src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png"
      },{
        id_2:5,
        name:"1.6",
        src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png"
      }]
    },{
      id_1:0,
      name_1:"智能制造学院",
      content_1:[{
        id_2:0,
        name:"1.1",
        src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png"
      },{
        id_2:1,
        name:"1.2",
        src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png"
      },{
        id_2:2,
        name:"1.3",
        src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png"
      },{
        id_2:3,
        name:"1.4",
        src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png"
      }]
    },{
      id_1:1,
      name_1:"软件学院",
      content_1:[{
        id_2:0,
        name:"2.1",
        src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png"
      },{
        id_2:1,
        name:"2.2",
        src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png"
      },{
        id_2:2,
        name:"2.3",
        src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png"
      },{
        id_2:3,
        name:"1.4",
        src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png"
      },{
        id_2:4,
        name:"1.5",
        src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png"
      }]
    },{
      id_1:3,
      name_1:"音乐学院",
      content_1:[{
        id_2:0,
        name:"1.1",
        src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png"
      },{
        id_2:1,
        name:"1.2",
        src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png"
      },{
        id_2:2,
        name:"1.3",
        src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png"
      },{
        id_2:3,
        name:"1.4",
        src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png"
      }]
    },{
      id_1:4,
      name_1:"张仲景国医国药学院",
      content_1:[{
        id_2:0,
        name:"2.1",
        src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png"
      },{
        id_2:1,
        name:"2.2",
        src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png"
      },{
        id_2:2,
        name:"2.3",
        src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png"
      },{
        id_2:3,
        name:"1.4",
        src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png"
      },{
        id_2:4,
        name:"1.5",
        src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png"
      }]
    }],
    scrollTop:0,

  },

  handleItemChange(e){
    
    const index=e.currentTarget.dataset.index;
    let temp=this.data.all_content[index];
    this.setData({
      currentIndex:index,
      temp,
      scrollTop:0
    });
  },

  /**
   * 生命周期函数--监听页面加载
   */
  onLoad: function (options) {
    
  },

  /**
   * 生命周期函数--监听页面初次渲染完成
   */
  onReady: function () {
    
  },

  /**
   * 生命周期函数--监听页面显示
   */
  onShow: function () {
    
  },

  /**
   * 生命周期函数--监听页面隐藏
   */
  onHide: function () {
    
  },

  /**
   * 生命周期函数--监听页面卸载
   */
  onUnload: function () {
    
  },

  /**
   * 页面相关事件处理函数--监听用户下拉动作
   */
  onPullDownRefresh: function () {
    
  },

  /**
   * 页面上拉触底事件的处理函数
   */
  onReachBottom: function () {
    
  },

  /**
   * 用户点击右上角分享
   */
  onShareAppMessage: function () {
    
  }
})