/* 
1 输入框绑定 值改变事件 input事件
  1 获取到输入框的值
  2 合法性判断 
  3 检验通过 把输入框的值 发送到后台
  4 返回的数据打印到页面上
2 防抖 （防止抖动） 定时器  节流 
  0 防抖 一般 输入框中 防止重复输入 重复发送请求
  1 节流 一般是用在页面下拉和上拉 
  1 定义全局的定时器id
 */
import { request } from "../../request/index.js";
import regeneratorRuntime from '../../lib/runtime/runtime';
Page({
  data: {
    goods:[],
    // 取消 按钮 是否显示
    isFocus:false,
    // 输入框的值
    inpValue:"",
    all_content:[
      [{
        id_1:0,
        name_1:"智能制造学院",
        content_1:[{
          id_2:0,
          name:"高等数学",
          src:"https://s1.ax1x.com/2020/09/05/wESbGt.jpg",
          cat_id:101,
          prince:20.5,
          author:"张三",
          version:"2019-08",
          original:68.5,
          publish:"光明出版社",
          type:"二手书"
        },{
          id_2:1,
          name:"机械制图",
          src:"https://s1.ax1x.com/2020/09/01/dvvV8x.jpg",
          cat_id:102,
          prince:10.0
        },{
          id_2:2,
          name:"1.3",
          src:"https://s1.ax1x.com/2020/09/01/dvvV8x.jpg",
          cat_id:103
        },{
          id_2:3,
          name:"1.4",
          src:"https://s1.ax1x.com/2020/09/01/dvvV8x.jpg",
          cat_id:104
        }]
      },{
        id_1:1,
        name_1:"软件学院",
        content_1:[{
          id_2:0,
          name:"2.1",
          src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png",
          cat_id:105
        },{
          id_2:1,
          name:"2.2",
          src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png",
          cat_id:106
        },{
          id_2:2,
          name:"2.3",
          src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png",
          cat_id:107
        },{
          id_2:3,
          name:"1.4",
          src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png",
          cat_id:108
        },{
          id_2:4,
          name:"1.5",
          src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png",
          cat_id:109
        }]
      },{
        id_1:2,
        name_1:"范蠡商学院",
        content_1:[{
          id_2:0,
          name:"1.1",
          src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png"
        },{
          id_2:1,
          name:"1.2",
          src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png"
        },{
          id_2:2,
          name:"1.3",
          src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png"
        },{
          id_2:3,
          name:"1.4",
          src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png"
        },{
          id_2:4,
          name:"1.5",
          src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png"
        },{
          id_2:5,
          name:"1.6",
          src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png"
        }]
      },{
        id_1:0,
        name_1:"智能制造学院",
        content_1:[{
          id_2:0,
          name:"1.1",
          src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png"
        },{
          id_2:1,
          name:"1.2",
          src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png"
        },{
          id_2:2,
          name:"1.3",
          src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png"
        },{
          id_2:3,
          name:"1.4",
          src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png"
        }]
      },{
        id_1:1,
        name_1:"软件学院",
        content_1:[{
          id_2:0,
          name:"2.1",
          src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png"
        },{
          id_2:1,
          name:"2.2",
          src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png"
        },{
          id_2:2,
          name:"2.3",
          src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png"
        },{
          id_2:3,
          name:"1.4",
          src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png"
        },{
          id_2:4,
          name:"1.5",
          src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png"
        }]
      },{
        id_1:3,
        name_1:"音乐学院",
        content_1:[{
          id_2:0,
          name:"1.1",
          src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png"
        },{
          id_2:1,
          name:"1.2",
          src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png"
        },{
          id_2:2,
          name:"1.3",
          src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png"
        },{
          id_2:3,
          name:"1.4",
          src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png"
        }]
      },{
        id_1:4,
        name_1:"张仲景国医国药学院",
        content_1:[{
          id_2:0,
          name:"2.1",
          src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png"
        },{
          id_2:1,
          name:"2.2",
          src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png"
        },{
          id_2:2,
          name:"2.3",
          src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png"
        },{
          id_2:3,
          name:"1.4",
          src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png"
        },{
          id_2:4,
          name:"1.5",
          src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png"
        }]
      }],
      [{
        id_1:0,
        name_1:"aaaa学院",
        content_1:[{
          id_2:0,
          name:"高数",
          src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png",
          prince:20.0
        },{
          id_2:1,
          name:"1.2",
          src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png"
        },{
          id_2:2,
          name:"1.3",
          src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png"
        },{
          id_2:3,
          name:"1.4",
          src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png"
        }]
      },{
        id_1:1,
        name_1:"软件学院",
        content_1:[{
          id_2:0,
          name:"2.1",
          src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png"
        },{
          id_2:1,
          name:"2.2",
          src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png"
        },{
          id_2:2,
          name:"2.3",
          src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png"
        },{
          id_2:3,
          name:"1.4",
          src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png"
        },{
          id_2:4,
          name:"1.5",
          src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png"
        }]
      },{
        id_1:2,
        name_1:"范蠡商学院",
        content_1:[{
          id_2:0,
          name:"1.1",
          src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png"
        },{
          id_2:1,
          name:"1.2",
          src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png"
        },{
          id_2:2,
          name:"1.3",
          src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png"
        },{
          id_2:3,
          name:"1.4",
          src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png"
        },{
          id_2:4,
          name:"1.5",
          src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png"
        },{
          id_2:5,
          name:"1.6",
          src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png"
        }]
      },{
        id_1:0,
        name_1:"智能制造学院",
        content_1:[{
          id_2:0,
          name:"1.1",
          src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png"
        },{
          id_2:1,
          name:"1.2",
          src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png"
        },{
          id_2:2,
          name:"1.3",
          src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png"
        },{
          id_2:3,
          name:"1.4",
          src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png"
        }]
      },{
        id_1:1,
        name_1:"软件学院",
        content_1:[{
          id_2:0,
          name:"2.1",
          src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png"
        },{
          id_2:1,
          name:"2.2",
          src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png"
        },{
          id_2:2,
          name:"2.3",
          src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png"
        },{
          id_2:3,
          name:"1.4",
          src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png"
        },{
          id_2:4,
          name:"1.5",
          src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png"
        }]
      },{
        id_1:3,
        name_1:"音乐学院",
        content_1:[{
          id_2:0,
          name:"1.1",
          src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png"
        },{
          id_2:1,
          name:"1.2",
          src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png"
        },{
          id_2:2,
          name:"1.3",
          src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png"
        },{
          id_2:3,
          name:"1.4",
          src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png"
        }]
      },{
        id_1:4,
        name_1:"张仲景国医国药学院",
        content_1:[{
          id_2:0,
          name:"2.1",
          src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png"
        },{
          id_2:1,
          name:"2.2",
          src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png"
        },{
          id_2:2,
          name:"2.3",
          src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png"
        },{
          id_2:3,
          name:"1.4",
          src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png"
        },{
          id_2:4,
          name:"1.5",
          src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png"
        }]
      }],
      [{
        id_1:0,
        name_1:"bbbb学院",
        content_1:[{
          id_2:0,
          name:"1.1",
          src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png"
        },{
          id_2:1,
          name:"1.2",
          src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png"
        },{
          id_2:2,
          name:"1.3",
          src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png"
        },{
          id_2:3,
          name:"1.4",
          src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png"
        }]
      },{
        id_1:1,
        name_1:"软件学院",
        content_1:[{
          id_2:0,
          name:"2.1",
          src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png"
        },{
          id_2:1,
          name:"2.2",
          src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png"
        },{
          id_2:2,
          name:"2.3",
          src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png"
        },{
          id_2:3,
          name:"1.4",
          src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png"
        },{
          id_2:4,
          name:"1.5",
          src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png"
        }]
      },{
        id_1:2,
        name_1:"范蠡商学院",
        content_1:[{
          id_2:0,
          name:"1.1",
          src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png"
        },{
          id_2:1,
          name:"1.2",
          src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png"
        },{
          id_2:2,
          name:"1.3",
          src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png"
        },{
          id_2:3,
          name:"1.4",
          src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png"
        },{
          id_2:4,
          name:"1.5",
          src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png"
        },{
          id_2:5,
          name:"1.6",
          src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png"
        }]
      },{
        id_1:0,
        name_1:"智能制造学院",
        content_1:[{
          id_2:0,
          name:"1.1",
          src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png"
        },{
          id_2:1,
          name:"1.2",
          src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png"
        },{
          id_2:2,
          name:"1.3",
          src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png"
        },{
          id_2:3,
          name:"1.4",
          src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png"
        }]
      },{
        id_1:1,
        name_1:"软件学院",
        content_1:[{
          id_2:0,
          name:"2.1",
          src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png"
        },{
          id_2:1,
          name:"2.2",
          src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png"
        },{
          id_2:2,
          name:"2.3",
          src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png"
        },{
          id_2:3,
          name:"1.4",
          src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png"
        },{
          id_2:4,
          name:"1.5",
          src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png"
        }]
      },{
        id_1:3,
        name_1:"音乐学院",
        content_1:[{
          id_2:0,
          name:"1.1",
          src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png"
        },{
          id_2:1,
          name:"1.2",
          src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png"
        },{
          id_2:2,
          name:"1.3",
          src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png"
        },{
          id_2:3,
          name:"1.4",
          src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png"
        }]
      },{
        id_1:4,
        name_1:"张仲景国医国药学院",
        content_1:[{
          id_2:0,
          name:"2.1",
          src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png"
        },{
          id_2:1,
          name:"2.2",
          src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png"
        },{
          id_2:2,
          name:"2.3",
          src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png"
        },{
          id_2:3,
          name:"1.4",
          src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png"
        },{
          id_2:4,
          name:"1.5",
          src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png"
        }]
      }],
      [{
        id_1:0,
        name_1:"dddd学院",
        content_1:[{
          id_2:0,
          name:"1.1",
          src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png"
        },{
          id_2:1,
          name:"1.2",
          src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png"
        },{
          id_2:2,
          name:"1.3",
          src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png"
        },{
          id_2:3,
          name:"1.4",
          src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png"
        }]
      },{
        id_1:1,
        name_1:"软件学院",
        content_1:[{
          id_2:0,
          name:"2.1",
          src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png"
        },{
          id_2:1,
          name:"2.2",
          src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png"
        },{
          id_2:2,
          name:"2.3",
          src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png"
        },{
          id_2:3,
          name:"1.4",
          src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png"
        },{
          id_2:4,
          name:"1.5",
          src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png"
        }]
      },{
        id_1:2,
        name_1:"范蠡商学院",
        content_1:[{
          id_2:0,
          name:"1.1",
          src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png"
        },{
          id_2:1,
          name:"1.2",
          src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png"
        },{
          id_2:2,
          name:"1.3",
          src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png"
        },{
          id_2:3,
          name:"1.4",
          src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png"
        },{
          id_2:4,
          name:"1.5",
          src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png"
        },{
          id_2:5,
          name:"1.6",
          src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png"
        }]
      },{
        id_1:0,
        name_1:"智能制造学院",
        content_1:[{
          id_2:0,
          name:"1.1",
          src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png"
        },{
          id_2:1,
          name:"1.2",
          src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png"
        },{
          id_2:2,
          name:"1.3",
          src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png"
        },{
          id_2:3,
          name:"1.4",
          src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png"
        }]
      },{
        id_1:1,
        name_1:"软件学院",
        content_1:[{
          id_2:0,
          name:"2.1",
          src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png"
        },{
          id_2:1,
          name:"2.2",
          src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png"
        },{
          id_2:2,
          name:"2.3",
          src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png"
        },{
          id_2:3,
          name:"1.4",
          src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png"
        },{
          id_2:4,
          name:"1.5",
          src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png"
        }]
      },{
        id_1:3,
        name_1:"音乐学院",
        content_1:[{
          id_2:0,
          name:"1.1",
          src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png"
        },{
          id_2:1,
          name:"1.2",
          src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png"
        },{
          id_2:2,
          name:"1.3",
          src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png"
        },{
          id_2:3,
          name:"1.4",
          src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png"
        }]
      },{
        id_1:4,
        name_1:"张仲景国医国药学院",
        content_1:[{
          id_2:0,
          name:"2.1",
          src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png"
        },{
          id_2:1,
          name:"2.2",
          src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png"
        },{
          id_2:2,
          name:"2.3",
          src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png"
        },{
          id_2:3,
          name:"1.4",
          src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png"
        },{
          id_2:4,
          name:"1.5",
          src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png"
        }]
      }],
      [{
        id_1:0,
        name_1:"eeeee学院",
        content_1:[{
          id_2:0,
          name:"1.1",
          src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png"
        },{
          id_2:1,
          name:"1.2",
          src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png"
        },{
          id_2:2,
          name:"1.3",
          src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png"
        },{
          id_2:3,
          name:"1.4",
          src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png"
        }]
      },{
        id_1:1,
        name_1:"软件学院",
        content_1:[{
          id_2:0,
          name:"2.1",
          src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png"
        },{
          id_2:1,
          name:"2.2",
          src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png"
        },{
          id_2:2,
          name:"2.3",
          src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png"
        },{
          id_2:3,
          name:"1.4",
          src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png"
        },{
          id_2:4,
          name:"1.5",
          src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png"
        }]
      },{
        id_1:2,
        name_1:"范蠡商学院",
        content_1:[{
          id_2:0,
          name:"1.1",
          src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png"
        },{
          id_2:1,
          name:"1.2",
          src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png"
        },{
          id_2:2,
          name:"1.3",
          src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png"
        },{
          id_2:3,
          name:"1.4",
          src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png"
        },{
          id_2:4,
          name:"1.5",
          src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png"
        },{
          id_2:5,
          name:"1.6",
          src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png"
        }]
      },{
        id_1:0,
        name_1:"智能制造学院",
        content_1:[{
          id_2:0,
          name:"1.1",
          src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png"
        },{
          id_2:1,
          name:"1.2",
          src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png"
        },{
          id_2:2,
          name:"1.3",
          src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png"
        },{
          id_2:3,
          name:"1.4",
          src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png"
        }]
      },{
        id_1:1,
        name_1:"软件学院",
        content_1:[{
          id_2:0,
          name:"2.1",
          src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png"
        },{
          id_2:1,
          name:"2.2",
          src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png"
        },{
          id_2:2,
          name:"2.3",
          src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png"
        },{
          id_2:3,
          name:"1.4",
          src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png"
        },{
          id_2:4,
          name:"1.5",
          src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png"
        }]
      },{
        id_1:3,
        name_1:"音乐学院",
        content_1:[{
          id_2:0,
          name:"1.1",
          src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png"
        },{
          id_2:1,
          name:"1.2",
          src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png"
        },{
          id_2:2,
          name:"1.3",
          src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png"
        },{
          id_2:3,
          name:"1.4",
          src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png"
        }]
      },{
        id_1:4,
        name_1:"张仲景国医国药学院",
        content_1:[{
          id_2:0,
          name:"2.1",
          src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png"
        },{
          id_2:1,
          name:"2.2",
          src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png"
        },{
          id_2:2,
          name:"2.3",
          src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png"
        },{
          id_2:3,
          name:"1.4",
          src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png"
        },{
          id_2:4,
          name:"1.5",
          src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png"
        }]
      }],
      [{
        id_1:0,
        name_1:"英语四级",
        content_1:[{
          id_2:0,
          name:"1.1",
          src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png"
        },{
          id_2:1,
          name:"1.2",
          src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png"
        },{
          id_2:2,
          name:"1.3",
          src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png"
        },{
          id_2:3,
          name:"1.4",
          src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png"
        }]
      },{
        id_1:1,
        name_1:"英语六级",
        content_1:[{
          id_2:0,
          name:"2.1",
          src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png"
        },{
          id_2:1,
          name:"2.2",
          src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png"
        },{
          id_2:2,
          name:"2.3",
          src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png"
        },{
          id_2:3,
          name:"1.4",
          src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png"
        },{
          id_2:4,
          name:"1.5",
          src:"https://api-hmugo-web.itheima.net/pyg/pic_floor03_2@2x.png"
        }]
      }],
    ],
  },
  TimeId:-1,
  // 输入框的值改变 就会触发的事件
  handleInput(e){
    // 1 获取输入框的值
    const {value}=e.detail;
    // 2 检测合法性
    if(!value.trim()){
      this.setData({
        goods:[],
        isFocus:false
      })
      // 值不合法
      return;
    }
    // 3 准备发送请求获取数据
    this.setData({
      isFocus:true
    })
    clearTimeout(this.TimeId);
    this.TimeId=setTimeout(() => {
      this.qsearch(value);
    }, 1000);
  },
  // 发送请求获取搜索建议 数据
  async qsearch(query){
    this.data.all_content.forEach(one => {
      one.forEach(two => {
        two.content_1.forEach(
          three => {
            if (three.name==query) {
              console.log(three);
              this.setData({
                goods:three
              });
              console.log(this.data.goods);
              return;
            }
          }
        )
      })
    });
  },
  // 点击 取消按钮
  handleCancel(){
    this.setData({
      inpValue:"",
      isFocus:false,
      goods:[]
    })
  }
})